In [1]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        # Initializing the instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Incrementing the total count of employees and total salary, whenever a new employee created.
        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        # Method to calculate the average salary.
        if cls.employee_count == 0:
            # return zero Since the employee count is Zero.
            return 0
        # return the avg. (total salary of employees)/(total no.of employees)
        return cls.total_salary / cls.employee_count


# Fulltime Employee class inheriting from Employee
class FulltimeEmployee(Employee):

    fulltime_Employee_count = 0

    def __init__(self, name, family, salary, department):
        # Calling the constructor of the parent class
        super().__init__(name, family, salary, department)

        FulltimeEmployee.fulltime_Employee_count += 1


# Creating instances of Employee and FulltimeEmployee
emp1 = Employee("Chandana", "Tallapragada", 40000, "Team Lead")
emp2 = Employee("Chiranjeevi", "Konidela", 50000, "Architect")
emp3 = FulltimeEmployee("Eswar", "Kandula", 60000, "Development")
emp4 = FulltimeEmployee("Sharmila", "Bhogadhi", 70000, "HR")
emp5 = FulltimeEmployee("Pawan Kalyan", "Konidela", 80000, "Manager")

# Print the average salary
print(f"Average Salary: {Employee.average_salary()}")

# Print the total number of employees
print(f"Total no.of Employees: {Employee.employee_count}")

# Print the total number of full time employees
print(f"Total no.of Full Time Employees: {FulltimeEmployee.fulltime_Employee_count}")


Average Salary: 60000.0
Total no.of Employees: 5
Total no.of Full Time Employees: 3


In [2]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)

Original array:
[ 4.28240563 15.54048618 18.04241923 19.62915625 15.53760052 15.47915834
  2.48247704 19.86425855 16.41071298 14.7470408  19.03915203  7.11929735
  6.93798352  8.003037   18.76245838  9.52415922 15.75946278  3.94966538
 15.02944705  6.96859833]

Reshaped array:
[[ 4.28240563 15.54048618 18.04241923  0.         15.53760052]
 [15.47915834  2.48247704  0.         16.41071298 14.7470408 ]
 [ 0.          7.11929735  6.93798352  8.003037   18.76245838]
 [ 9.52415922  0.          3.94966538 15.02944705  6.96859833]]
